<a href="https://colab.research.google.com/github/varunkamate/Text_Preprocessing_NLP/blob/main/Text_Representation_Word_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# Bag of words

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({"text":["people watch ironman",
                         "ironman watch ironman",
                         "people write comment",
                          "ironman write comment"],"output":[1,0,1,0]})

In [3]:
df

text  output
0   people watch ironman       1
1  ironman watch ironman       0
2   people write comment       1
3  ironman write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [5]:
a=cv.fit_transform(df["text"])

vocabulary

In [6]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'ironman': 1, 'write': 4, 'comment': 0}


In [7]:
a.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [8]:
print(a[0].toarray())
print(a[1].toarray())
print(a[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [9]:
# new
cv.transform(['ironman watch ironman']).toarray()

array([[0, 2, 0, 1, 0]])

#  N-grams

In [10]:
df=pd.DataFrame({"text":["people watch ironman",
                         "ironman watch ironman",
                         "people write comment",
                          "ironman write comment"],"output":[1,0,1,0]})

In [11]:
df

text  output
0   people watch ironman       1
1  ironman watch ironman       0
2   people write comment       1
3  ironman write comment       0

In [12]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [13]:
b=cv.fit_transform(df["text"])

In [14]:
print(cv.vocabulary_)

{'people watch': 2, 'watch ironman': 4, 'ironman watch': 0, 'people write': 3, 'write comment': 5, 'ironman write': 1}


In [15]:
print(b[0].toarray())
print(b[1].toarray())
print(b[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


# TF-IDF (Term frequency- Inverse document frequency)

In [16]:
df=pd.DataFrame({"text":["people watch ironman",
                         "ironman watch ironman",
                         "people write comment",
                          "ironman write comment"],"output":[1,0,1,0]})

In [17]:
df

text  output
0   people watch ironman       1
1  ironman watch ironman       0
2   people write comment       1
3  ironman write comment       0

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [19]:
arr = tfid.fit_transform(df['text']).toarray()

In [20]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [21]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
